name: Maven Build

on:
  push:
    branches: [ main, master ] # Definisci su quali branch attivare il workflow (es. main, master)
  pull_request:
    branches: [ main, master ] # Definisci su quali branch attivare il workflow per le pull request

jobs:
  build:

    runs-on: ubuntu-latest # Specifica l'ambiente in cui eseguire il job

    steps:
    - uses: actions/checkout@v3 # Esegue il checkout del codice dal repository

    - name: Set up JDK 11 # Configura l'ambiente Java (puoi scegliere la versione desiderata)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # Distribuzione OpenJDK

    - name: Build with Maven # Esegue la build del progetto Maven
      run: mvn clean install -B # Il flag -B (batch mode) assicura un output più pulito
